// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEjL3gdeXom4WZHhONZxiDOeDC4BEuYYo',
    appId: '1:594086372653:web:d753636dd8d2bb0adb1fa4',
    messagingSenderId: '594086372653',
    projectId: 'new-project-fcdcc',
    authDomain: 'new-project-fcdcc.firebaseapp.com',
    storageBucket: 'new-project-fcdcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv4rBYSSV2O36tupIj266ty9Fo656Fm7A',
    appId: '1:594086372653:android:dddcc671be18c719db1fa4',
    messagingSenderId: '594086372653',
    projectId: 'new-project-fcdcc',
    storageBucket: 'new-project-fcdcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32Wd2jFZFK5Gb4J7J1HKARpLrn2Y4XDk',
    appId: '1:594086372653:ios:57693848dd92e4aadb1fa4',
    messagingSenderId: '594086372653',
    projectId: 'new-project-fcdcc',
    storageBucket: 'new-project-fcdcc.appspot.com',
    iosBundleId: 'com.example.cc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA32Wd2jFZFK5Gb4J7J1HKARpLrn2Y4XDk',
    appId: '1:594086372653:ios:57693848dd92e4aadb1fa4',
    messagingSenderId: '594086372653',
    projectId: 'new-project-fcdcc',
    storageBucket: 'new-project-fcdcc.appspot.com',
    iosBundleId: 'com.example.cc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEjL3gdeXom4WZHhONZxiDOeDC4BEuYYo',
    appId: '1:594086372653:web:dd491b6a558df8d6db1fa4',
    messagingSenderId: '594086372653',
    projectId: 'new-project-fcdcc',
    authDomain: 'new-project-fcdcc.firebaseapp.com',
    storageBucket: 'new-project-fcdcc.appspot.com',
  );
}
